name: Build & Deploy Engine
on: [push, pull_request]

permissions:
  contents: write

env:
  RELEASES_REPO: berkchy/phantom-releases

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Prepare release tag
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ""
          GH_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        run: |
          if [[ "${GITHUB_REF_NAME}" == "master" ]]; then
            TAG_NAME="continuous"
          else
            TAG_NAME="continuous-${GITHUB_REF_NAME}"
          fi

          if gh release view "$TAG_NAME" --repo "${{ env.RELEASES_REPO }}" >/dev/null 2>&1; then
            gh release delete "$TAG_NAME" --yes --cleanup-tag --repo "${{ env.RELEASES_REPO }}"
          fi

          gh release create "$TAG_NAME" \
            --title "Xash3D FWGS Continuous ${GITHUB_REF_NAME} Build" \
            --prerelease \
            --repo "${{ env.RELEASES_REPO }}"

#  cleanup:
#    runs-on: self-hosted
#    steps:
#    - name: Cleanup
#      run: rm -rf .* || true
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    needs: [prepare-release]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            targetos: android
            targetarch: multiarch
          - os: windows-latest
            targetos: win32
            targetarch: amd64
          - os: windows-2022 # always use the oldest possible for 32-bit because of older compilers, and better support of certain legacy OSes
            targetos: win32
            targetarch: i386
    env:
      SDL_VERSION: 2.32.10
      FFMPEG_VERSION: 8.1
      GH_CPU_ARCH: ${{ matrix.targetarch }}
      GH_CPU_OS: ${{ matrix.targetos }}
      GH_CROSSCOMPILING: ${{ matrix.cross }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Install dependencies
      run: bash scripts/gha/deps_${{ matrix.targetos }}.sh
    - name: Build engine
      env:
        FWGS_PFX_PASSWORD: ${{ secrets.FWGS_PFX_PASSWORD }}
      run: bash scripts/gha/build_${{ matrix.targetos }}.sh
    - name: Upload engine release asset
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      with:
        repository: ${{ env.RELEASES_REPO }}
        token: ${{ secrets.RELEASES_TOKEN }}
        tag_name: ${{ github.ref_name == 'master' && 'continuous' || format('continuous-{0}', github.ref_name) }}
        files: artifacts/*
        fail_on_unmatched_files: true
        overwrite_files: true
